name: json_request
description: json config to dart request code.
version: 0.1.0

environment:
  sdk: ">=2.13.3 <3.0.0"

dependencies:
  dio: ^4.0.4
  args: ^2.1.1
  build: ^2.0.3
  glob: ^2.0.1
  logging: ^1.0.1
  io: ^1.0.3
  path: ^1.8.0
dev_dependencies:
  test: ^1.5.1
  lint: ^1.0.0
